-- =============================================
-- AI Smart Helpdesk - Supabase Schema
-- Run this in your Supabase SQL Editor
-- =============================================

-- 1. Enable Vector Extension for RAG
create extension if not exists vector;

-- 2. Profiles Table (Public metadata for Auth users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text not null,
  role text check (role in ('admin', 'agent', 'customer')) default 'customer',
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tickets Table
create table public.tickets (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.profiles(id) not null,
  subject text not null,
  description text not null,
  status text check (status in ('open', 'resolved', 'closed')) default 'open',
  priority text check (priority in ('low', 'medium', 'high', 'critical')) default 'medium',
  sentiment_score float,
  tags text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Messages Table (Stores Chat & Embeddings)
create table public.messages (
  id bigint generated by default as identity primary key,
  ticket_id bigint references public.tickets(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) not null,
  content text not null,
  embedding vector(1536),
  is_internal boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. RLS Policies (Security)
alter table public.profiles enable row level security;
alter table public.tickets enable row level security;
alter table public.messages enable row level security;

-- Profiles policies
create policy "Public profiles are viewable by everyone" 
  on public.profiles for select using (true);

create policy "Users can insert their own profile" 
  on public.profiles for insert with check (auth.uid() = id);

create policy "Users can update their own profile" 
  on public.profiles for update using (auth.uid() = id);

-- Tickets policies
create policy "Agents and admins view all tickets" 
  on public.tickets for select using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('agent', 'admin'))
  );

create policy "Customers view own tickets" 
  on public.tickets for select using (auth.uid() = customer_id);

create policy "Authenticated users can create tickets" 
  on public.tickets for insert with check (auth.uid() = customer_id);

create policy "Agents can update tickets" 
  on public.tickets for update using (
    exists (select 1 from public.profiles where id = auth.uid() and role in ('agent', 'admin'))
  );

-- Messages policies
create policy "View messages for accessible tickets" 
  on public.messages for select using (true);

create policy "Authenticated users can send messages" 
  on public.messages for insert with check (auth.uid() = sender_id);

-- 6. Vector Search Function (RPC for RAG)
create or replace function match_messages (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    messages.id,
    messages.content,
    1 - (messages.embedding <=> query_embedding) as similarity
  from messages
  where 1 - (messages.embedding <=> query_embedding) > match_threshold
  order by messages.embedding <=> query_embedding
  limit match_count;
end;
$$;

-- 7. Create indexes for better performance
create index if not exists tickets_customer_id_idx on public.tickets(customer_id);
create index if not exists tickets_status_idx on public.tickets(status);
create index if not exists messages_ticket_id_idx on public.messages(ticket_id);

-- 8. Function to handle new user signup (creates profile automatically)
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$;

-- Trigger to auto-create profile on signup
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
